//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_WBHLI74Ns"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "37dh7kcap7bmlfmb9ni6o72dh4"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "t4q1qb254ci3lqiq6kkt16kjrqgup9t6g7fufkj10or8hf98jcc"

let CognitoIdentityPoolId = "us-east-1:1596f251-5106-4370-ae3b-f623988b6c46"
